In [5]:
# data ?
# how to measure data?
# mean 
# median 
# mode

# variance 
# std

# covraiance 
# correlation 

# quartilies
# outliers 

# probability

In [1]:
import numpy as np 

In [2]:
np.random.seed(123)
data = np.random.randint(1,100,(100 , 5))

In [4]:
# # data
# x first four cols
# y last col 
# x_train , x_test   (x) , y_train , y_test (y)

In [7]:
def trin_test_split(data , perc = .5):
    x = data[: , :-1]
    y = data[: , -1]
    n_rows  = int(len(data) * perc) 
    x_train , x_test = x[:n_rows , :] , x[n_rows: , :]
    y_train , y_test = y[ 0 : n_rows] , y[ n_rows :  ]
    return x_train , x_test , y_train , y_test 

In [11]:
x_train , x_test , y_train , y_test = trin_test_split(data , .7  )

In [12]:
x_train.shape

(70, 4)

In [13]:
x_test.shape

(30, 4)

In [14]:
from sklearn.model_selection import train_test_split

In [15]:
x = data[: , 0:-1]
y = data[: , -1]

In [20]:
x_train_ , x_test , y_train , y_test = train_test_split(x , y , train_size=.8 )

In [21]:
x_train_.shape

(80, 4)

In [24]:
(20 + 25 + 23 ) / 3

22.666666666666668

In [25]:
# 20 , 23 , 25 , 90   = (23 + 25) / 2   = 24 

In [27]:
matrix = np.array([ [1,2,3,4,3] , [2,3,4,5,6] , [3,4,5,6,7] ])
matrix

array([[1, 2, 3, 4, 3],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [28]:
np.mean(matrix)

3.8666666666666667

In [29]:
np.mean(matrix , axis= 0 )  # axis = 0  >>  colsssss

array([2.        , 3.        , 4.        , 5.        , 5.33333333])

In [30]:
np.mean(matrix , axis= 1 )  # axis = 1  >>  rowssssss

array([2.6, 4. , 5. ])

In [33]:
matrix[0].sum() / len(matrix[0])

2.6

In [34]:
np.median(matrix)

4.0

In [36]:
np.median(matrix , axis= 0 )  # axis = 0  >>  colsssss

array([2., 3., 4., 5., 6.])

In [37]:
np.median(matrix , axis= 1 )  # axis = 1  >>  rowssssss

array([3., 4., 5.])

In [38]:
matrix

array([[1, 2, 3, 4, 3],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [39]:
np.var(matrix)

2.648888888888889

In [40]:
np.var(matrix , axis = 0 )

array([0.66666667, 0.66666667, 0.66666667, 0.66666667, 2.88888889])

In [41]:
np.var(matrix , axis = 1 )

array([1.04, 2.  , 2.  ])

In [42]:
np.std(matrix )

1.6275407487644937

In [43]:
np.std(matrix , axis = 0)

array([0.81649658, 0.81649658, 0.81649658, 0.81649658, 1.69967317])

In [44]:
np.std(matrix , axis = 1)

array([1.0198039 , 1.41421356, 1.41421356])

In [49]:
x = np.array([1,2,3,4,5,6,7,8,9])
y = np.array([9,8,7,6,5,4,3,2,1])
np.cov(x,y)[0,1]

-7.5

In [52]:
x = np.array([1,2,3,4,5,6,7,8,8])
y = np.array([9,8,7,6,5,4,3,2,1])
np.corrcoef(x,y)[1,0]

-0.9941002434954167

In [53]:
d = np.array([5,40,45,46,48,50,55,500])

In [56]:
q1 = np.quantile(d , .25)
q2 = np.quantile(d , .50)
q3 = np.quantile(d , .75)

In [57]:
IQR = q3 - q1 
IQR

7.5

In [58]:
lower = q1 - (1.5 * IQR)
lower

32.5

In [59]:
upper = q3 + (1.5 * IQR)
upper

62.5

In [60]:
d <= upper

array([ True,  True,  True,  True,  True,  True,  True, False])

In [61]:
d >= lower

array([False,  True,  True,  True,  True,  True,  True,  True])

In [65]:
d[(d >= lower) & (d <= upper)]

array([40, 45, 46, 48, 50, 55])