In [1]:
m1 = [[1,2,3] , [2,3,4]]
m1

[[1, 2, 3], [2, 3, 4]]

In [2]:
m2 = [[1,2,3] , [2,3,4]]
m2

[[1, 2, 3], [2, 3, 4]]

In [3]:
# [[2,4,6] , [2,6,8]]

In [5]:
[  [ x + y for x , y in zip(a,b)] for a ,b in zip(m1 , m2)]

[[2, 4, 6], [4, 6, 8]]

In [13]:
res = []
for i in range(len(m2)):
    lst = []
    for j in range(len(m2[0])):
        lst.append(m1[i][j] + m2[i][j])
    res.append(lst)

In [14]:
res

[[2, 4, 6], [4, 6, 8]]

In [18]:
import numpy as np 

In [16]:
m1

[[1, 2, 3], [2, 3, 4]]

In [28]:
matrix = np.array([[1, 2, 3], [2, 3,4]])
matrix

array([[1, 2, 3],
       [2, 3, 4]])

In [29]:
type(matrix)

numpy.ndarray

In [30]:
matrix.shape

(2, 3)

In [31]:
print("Number of rows is:" ,matrix.shape[0] )

Number of rows is: 2


In [32]:
print("Number of cols is:" , matrix.shape[1])

Number of cols is: 3


In [33]:
lst = [ 1,2,3 ]
lst * 2 

[1, 2, 3, 1, 2, 3]

In [36]:
arr1 = np.array(lst)
arr1

array([1, 2, 3])

In [37]:
arr1 * 2 

array([2, 4, 6])

In [38]:
m1

[[1, 2, 3], [2, 3, 4]]

In [39]:
m2

[[1, 2, 3], [2, 3, 4]]

In [40]:
mat1 = np.array(m1)
mat2 = np.array(m2)

In [41]:
mat1 + mat2

array([[2, 4, 6],
       [4, 6, 8]])

In [42]:
mat1

array([[1, 2, 3],
       [2, 3, 4]])

In [44]:
mat1 - mat2

array([[0, 0, 0],
       [0, 0, 0]])

In [47]:
arr1  = np.array([1,2,3,4,3,4,5,4,5,6,7,8,9])
arr1

array([1, 2, 3, 4, 3, 4, 5, 4, 5, 6, 7, 8, 9])

In [48]:
arr1 < 5

array([ True,  True,  True,  True,  True,  True, False,  True, False,
       False, False, False, False])

In [49]:
arr1[arr1 < 5]

array([1, 2, 3, 4, 3, 4, 4])

In [50]:
arr1[arr1 > 5 ]

array([6, 7, 8, 9])

In [52]:
# np.arange(start , stop , step)

In [54]:
arr2 = np.arange(1 , 50 , 2)
arr2

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49])

In [55]:
len(arr2)

25

In [56]:
arr2.size

25

In [57]:
arr2.shape

(25,)

In [59]:
arr2.reshape((5,5))

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29],
       [31, 33, 35, 37, 39],
       [41, 43, 45, 47, 49]])

In [60]:
arr2.reshape((25,1))

array([[ 1],
       [ 3],
       [ 5],
       [ 7],
       [ 9],
       [11],
       [13],
       [15],
       [17],
       [19],
       [21],
       [23],
       [25],
       [27],
       [29],
       [31],
       [33],
       [35],
       [37],
       [39],
       [41],
       [43],
       [45],
       [47],
       [49]])

In [64]:
arr2.reshape((-1,1))

array([[ 1],
       [ 3],
       [ 5],
       [ 7],
       [ 9],
       [11],
       [13],
       [15],
       [17],
       [19],
       [21],
       [23],
       [25],
       [27],
       [29],
       [31],
       [33],
       [35],
       [37],
       [39],
       [41],
       [43],
       [45],
       [47],
       [49]])

In [66]:
arr2.reshape((5,5))

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29],
       [31, 33, 35, 37, 39],
       [41, 43, 45, 47, 49]])

In [67]:
arr2.reshape((5,5,1))

array([[[ 1],
        [ 3],
        [ 5],
        [ 7],
        [ 9]],

       [[11],
        [13],
        [15],
        [17],
        [19]],

       [[21],
        [23],
        [25],
        [27],
        [29]],

       [[31],
        [33],
        [35],
        [37],
        [39]],

       [[41],
        [43],
        [45],
        [47],
        [49]]])

In [70]:
np.linspace(1,10 , 4 ).reshape((2,2))

array([[ 1.,  4.],
       [ 7., 10.]])

In [76]:
np.random.random() # 0 ... 1 

0.06859402708909346

In [102]:
# np.random.randint(start,stop , (shape) )
np.random.seed(123)
data = np.random.randint(1 , 20 , (5,5))
data

array([[14,  3,  3,  7, 18],
       [11,  2,  1, 18, 16],
       [10,  1, 15,  1, 16],
       [15,  5,  1, 17,  5],
       [18,  4,  3,  8,  3]])

In [103]:
data[0]

array([14,  3,  3,  7, 18])

In [104]:
data[-1]

array([18,  4,  3,  8,  3])

In [105]:
data[0][0]

14

In [106]:
# matrix[rows , cols]   matrix[ start : end , start : end]

In [107]:
data

array([[14,  3,  3,  7, 18],
       [11,  2,  1, 18, 16],
       [10,  1, 15,  1, 16],
       [15,  5,  1, 17,  5],
       [18,  4,  3,  8,  3]])

In [110]:
data[ 0 : 2 ]  # or data[ 0 : 2 , : ]

array([[14,  3,  3,  7, 18],
       [11,  2,  1, 18, 16]])

In [111]:
data[1 : 4 ]

array([[11,  2,  1, 18, 16],
       [10,  1, 15,  1, 16],
       [15,  5,  1, 17,  5]])

In [119]:
data[-1: -4 :-1]

array([[18,  4,  3,  8,  3],
       [15,  5,  1, 17,  5],
       [10,  1, 15,  1, 16]])

In [117]:
data

array([[14,  3,  3,  7, 18],
       [11,  2,  1, 18, 16],
       [10,  1, 15,  1, 16],
       [15,  5,  1, 17,  5],
       [18,  4,  3,  8,  3]])

In [122]:
data[ : , 0:1]

array([[14],
       [11],
       [10],
       [15],
       [18]])

In [123]:
data[ : , -1:]

array([[18],
       [16],
       [16],
       [ 5],
       [ 3]])

In [125]:
data[1 : 3 , 1 : 4]

array([[ 2,  1, 18],
       [ 1, 15,  1]])

In [131]:
z = np.zeros((5,5))
z

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [132]:
z.astype(int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [130]:
np.ones((5,5) , dtype = float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [142]:
np.full((5,5) , 0)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])